name: Build and Test eBPF CLI Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm gcc make libbpf-dev build-essential iproute2 git wget curl bpfcc-tools libelf-dev iputils-ping net-tools python3 python3-pip python3-setuptools kmod libmnl-dev linux-libc-dev
          
          # Install kernel headers needed for eBPF development
          sudo apt-get install -y linux-headers-$(uname -r) linux-headers-generic
          
          # Install additional glibc development headers
          sudo apt-get install -y libc6-dev libc6-dev-i386

          # Create symbolic links for missing asm headers
          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
          
          # Create symbolic links for missing bits headers
          sudo ln -s /usr/include/x86_64-linux-gnu/bits /usr/include/bits

      - name: Verify project structure
        run: |
          ls -la
          ls -la include  # Check if the include directory exists
          ls -la src       # Check if the src directory exists
          ls -la Makefile  # Ensure Makefile exists at the root

      - name: Build the eBPF CLI Tool
        run: make

      - name: List build output
        run: ls -la  # List all files to ensure the binaries are created

      - name: Find cli_tool binary
        run: find . -name 'cli_tool'  # Find the location of the cli_tool binary

      - name: Set correct permissions for cli_tool
        run: chmod +x ./cli_tool || echo "cli_tool not found"  # Ensure the cli_tool binary is executable

      - name: Run the eBPF CLI Tool
        run: ./cli_tool --start
